knp_snappy:
    pdf:
        enabled:    true
        # binary:     '%kernel.build_dir%/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'
        options:    []
    image:
        enabled:    true
        # binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []

        