### Login
POST http://localhost:8000/api/login_check
content-type: application/json

{
    "username":"user@user.com",
    "password":"user"
}

### User create
GET http://localhost:8000/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjA4MjI2MzUsImV4cCI6MTY2MDgyNjIzNSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckB1c2VyLmNvbSJ9.cav9GazwNMiOCj7CbqvZkf2T_Oq7foFtSuWVqExo1KJUpNNrDQnLcjJEXH56LK9X-q_u6U9knGEnW10UwNK50BjWnsN6B0qGrpEQGO2F40PxZrGHc10jacEv9-Pa5s94osecTrzu1lxlYdBBdFS4pP31WurHgDFfC0OIjMtwt0VAFlB8ttoP_V4aER-72RgunpPPs7rIMSCmWmG0_yWVRFoWb9pB72QIPJLR_pR0nMAeygTerSOBUluqoflW1Ucu1A10EyeMrBI_kg4fVg3uzYR4m11IrLfesWTdcLJXXyEBuhwlO386cdB49XDZfhTURG-5dWQXtev4baMO_pDjtA

### User create
POST http://localhost:8000/api/v1/users/create
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password"
    
}

### User update $2y$13$ckAh0IP2svGr.4KuhpxBKeyeNLRVRZGJapLAoc1mS931ZkQfd5Q9W
PATCH http://localhost:8000/api/v1/users/update
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjA4MjYzMzgsImV4cCI6MTY2MzQxODMzOCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckB1c2VyLmNvbSJ9.JMTmu3475KhOIRbq5eu8vhIqXCux1dIGoec47V4G2ewPUfDL-TNcjd7dIu04jbYtxsYpzWscy5m2JtQi1y1KD0JZ9-Q6CrGTW34HXOskkOEd9KZ_FlRS2YRI7HzqMmY7fncOcAhml-ZVA3wpgKw3KM6RWR4QDa2P3lPAmfq_LYJy00gUdUovOxpJaYQ4Ka1y0MPzLKA_Bwyn2agSP6TP3y_fAR_pJlMIoEk2AwYSNYgiDHr8OIXuAc98CSWxyELscgXrwLbfBloD__tESp0wfaR4hmAGJQU7gWXlLS6u2iDWAiVj6gvskAGcNwnGEH0KZfDPpNYyyV44A4gHR1ar2A

{
    "firstname": "toto",
    "password": "tata"
}

### Categories list
GET http://localhost:8000/api/v1/categories
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjA4MTQyMzcsImV4cCI6MTY2MDgxNzgzNywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckB1c2VyLmNvbSJ9.fM7QV1IWm4JAxpNfHDUYcL2izgiANOtnFpyapbBW4evX9HlkymwdaE0JqUgHNxLWV7oJdGTlEkHLjohR62y7gWGbSGRK0YX69fJaSUeDAON70MOxxFJRbo1MM6MiLLahH0aBrRcKUtsFavb5o7RAa4Jpoq7VVPvByZVhTw49aduhnQQcWBpystpJ8U4Ln9_gk-nOwUPrLnFV0AqMFqwOk3WmG1zje6rKxLJRjv2kAv7VODABQfoB1kuZPp_OfVp9EULinA6OTOs6u8kxcHhvVmQwCkm7rPLrgIz-_IMrEjiN9ue2-gPTIArPTDRwccE5xhACrv1iWEDdbh0W14RPcQ

### Category Products (fruits)
##
## http://localhost:8000/api/v1/categories/{slug}/products
GET http://localhost:8000/api/v1/categories/fruits/products

### Category Products (legumes)
GET http://localhost:8000/api/v1/categories/legumes/products

### Category Products (produits-transformes)
GET http://localhost:8000/api/v1/categories/produits-transformes/products

### Products list
GET http://localhost:8000/api/v1/products

### One product (poivron)
##
## http://localhost:8000/api/v1/products/{slug}
GET http://localhost:8000/api/v1/products/poivron

### Depots list
GET http://localhost:8000/api/v1/depots

### One depot (jordane-flatley)
##
## http://localhost:8000/api/v1/depots/{slug}
GET http://localhost:8000/api/v1/depots/jordane-flatley

### All carts
GET http://localhost:8000/api/v1/carts

### little cart
GET http://localhost:8000/api/v1/carts/small

### big cart
GET http://localhost:8000/api/v1/carts/big

### List orders of a user
GET http://localhost:8000/api/v1/orders/user
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjA4MjYzMzgsImV4cCI6MTY2MzQxODMzOCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckB1c2VyLmNvbSJ9.JMTmu3475KhOIRbq5eu8vhIqXCux1dIGoec47V4G2ewPUfDL-TNcjd7dIu04jbYtxsYpzWscy5m2JtQi1y1KD0JZ9-Q6CrGTW34HXOskkOEd9KZ_FlRS2YRI7HzqMmY7fncOcAhml-ZVA3wpgKw3KM6RWR4QDa2P3lPAmfq_LYJy00gUdUovOxpJaYQ4Ka1y0MPzLKA_Bwyn2agSP6TP3y_fAR_pJlMIoEk2AwYSNYgiDHr8OIXuAc98CSWxyELscgXrwLbfBloD__tESp0wfaR4hmAGJQU7gWXlLS6u2iDWAiVj6gvskAGcNwnGEH0KZfDPpNYyyV44A4gHR1ar2A

### List an order
GET http://localhost:8000/api/v1/orders/78
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjA4MjYzMzgsImV4cCI6MTY2MzQxODMzOCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckB1c2VyLmNvbSJ9.JMTmu3475KhOIRbq5eu8vhIqXCux1dIGoec47V4G2ewPUfDL-TNcjd7dIu04jbYtxsYpzWscy5m2JtQi1y1KD0JZ9-Q6CrGTW34HXOskkOEd9KZ_FlRS2YRI7HzqMmY7fncOcAhml-ZVA3wpgKw3KM6RWR4QDa2P3lPAmfq_LYJy00gUdUovOxpJaYQ4Ka1y0MPzLKA_Bwyn2agSP6TP3y_fAR_pJlMIoEk2AwYSNYgiDHr8OIXuAc98CSWxyELscgXrwLbfBloD__tESp0wfaR4hmAGJQU7gWXlLS6u2iDWAiVj6gvskAGcNwnGEH0KZfDPpNYyyV44A4gHR1ar2A

### Create an order
POST http://localhost:8000/api/v1/orders/create
content-type: application/json

{
    "depot": {
        "id": "1" 
    },
    "price": 0,
    "payment_status": "no",
    "cart": {
        "type_cart": "small",
        "quantity": 0
    },
    "product": {
        "id": "1",
        "quantity": 0
    }
}