### Login
POST http://localhost:8000/api/login_check
content-type: application/json

{
    "username":"user@user.com",
    "password":"user"
}

### User create
GET http://localhost:8000/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjA4MzczMzQsImV4cCI6MTY2MzQyOTMzNCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckB1c2VyLmNvbSJ9.BseR51ovntaVpe5AF9eEKS8p-FPgzH5nxifCypPVCyujnF9c75FBZVRVJGCQ6W0BC4J32xF3EMSVCkH60gI3UQCzXgPM2y0PaWSmT_Eu7yPS_GkFs7Q3fFjC5Ys4bJHA8vVEOoL4dQPaGjmrxgpy_iC0U3hpJ8Jitm0EIBd4ddmHbp0qKV-PCcf6IAHimDYXxt6G3_Sa5-wbAiGqHGz3HRvN-uLaTlC0clszpKrjBDAAval7eFUuKFSEreI76uK8rsMENZdNkZktxC3rXwIRU8WY4ahULUfajIcdh-NeX0S3iOmOWov4w_XyeM08aIfinjlEkeq6N2FPmSNyb-Avjg

### User create
POST http://localhost:8000/api/v1/users/create
Content-Type: application/json

{
    "email": "tata@tata.com",
    "password": "password",
    "firstname": null,
    "lastname": null ,
    "phone": null,
    "address": null
}

### User update
PATCH http://localhost:8000/api/v1/users/update
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjA4MjYzMzgsImV4cCI6MTY2MzQxODMzOCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckB1c2VyLmNvbSJ9.JMTmu3475KhOIRbq5eu8vhIqXCux1dIGoec47V4G2ewPUfDL-TNcjd7dIu04jbYtxsYpzWscy5m2JtQi1y1KD0JZ9-Q6CrGTW34HXOskkOEd9KZ_FlRS2YRI7HzqMmY7fncOcAhml-ZVA3wpgKw3KM6RWR4QDa2P3lPAmfq_LYJy00gUdUovOxpJaYQ4Ka1y0MPzLKA_Bwyn2agSP6TP3y_fAR_pJlMIoEk2AwYSNYgiDHr8OIXuAc98CSWxyELscgXrwLbfBloD__tESp0wfaR4hmAGJQU7gWXlLS6u2iDWAiVj6gvskAGcNwnGEH0KZfDPpNYyyV44A4gHR1ar2A

{
    "firstname": "toto",
    "lastname": "coco",
    "password": "user",
    "currentpassword": "bobo"
}

### Cate lgoriesist
GET http://localhost:8000/api/v1/categories
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjA4Mzc1MTgsImV4cCI6MTY2MzQyOTUxOCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckB1c2VyLmNvbSJ9.IV_PMlxucSe3ewjC-OdFR_upNOZw5EH6bGHvnDZOJmO2v-zD8tM9ZRDO6xfzNoQXvOSX93UySFhG1Pt6Pm4kW9QkWUmbtevOQwn4bTW10c374uh9OKT5i-pFBDw0lxlFMKzKDFdLj_ZM6pvK7AxjWrXlUaSeSD9HzbgfbLjUiBVvicmGu0HTYFMewyNLcxR2RHOLYNR8R3gq6YdFMEx09UEvZ-q1jEoxxUFVAOV9lexuUYxWMk9QKSOsK4YJNSb6L_cKIhZae2sP5L4YKhgpGZ9bPk2iP05vIcYydnsSUq-VzDq9OQ3wtIbXVKMbnB-FoSaqHfGSAw2OzQquMBaznA

### Category Products (fruits)
##
## http://localhost:8000/api/v1/categories/{slug}/products
GET http://localhost:8000/api/v1/categories/fruits/products

### Category Products (legumes)
GET http://localhost:8000/api/v1/categories/legumes/products

### Category Products (produits-transformes)
GET http://localhost:8000/api/v1/categories/produits-transformes/products

### Products list
GET http://localhost:8000/api/v1/products

### One product (poivron)
##
## http://localhost:8000/api/v1/products/{slug}
GET http://localhost:8000/api/v1/products/poivron

### Depots list
GET http://localhost:8000/api/v1/depots

### One depot (jordane-flatley)
##
## http://localhost:8000/api/v1/depots/{slug}
GET http://localhost:8000/api/v1/depots/jordane-flatley

### All carts
GET http://localhost:8000/api/v1/carts

### little cart
GET http://localhost:8000/api/v1/carts/small

### big cart
GET http://localhost:8000/api/v1/carts/big

### List orders of a user
GET http://localhost:8000/api/v1/orders/user
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjA4MjYzMzgsImV4cCI6MTY2MzQxODMzOCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckB1c2VyLmNvbSJ9.JMTmu3475KhOIRbq5eu8vhIqXCux1dIGoec47V4G2ewPUfDL-TNcjd7dIu04jbYtxsYpzWscy5m2JtQi1y1KD0JZ9-Q6CrGTW34HXOskkOEd9KZ_FlRS2YRI7HzqMmY7fncOcAhml-ZVA3wpgKw3KM6RWR4QDa2P3lPAmfq_LYJy00gUdUovOxpJaYQ4Ka1y0MPzLKA_Bwyn2agSP6TP3y_fAR_pJlMIoEk2AwYSNYgiDHr8OIXuAc98CSWxyELscgXrwLbfBloD__tESp0wfaR4hmAGJQU7gWXlLS6u2iDWAiVj6gvskAGcNwnGEH0KZfDPpNYyyV44A4gHR1ar2A

### List an order
GET http://localhost:8000/api/v1/orders/78
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjA4MjYzMzgsImV4cCI6MTY2MzQxODMzOCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckB1c2VyLmNvbSJ9.JMTmu3475KhOIRbq5eu8vhIqXCux1dIGoec47V4G2ewPUfDL-TNcjd7dIu04jbYtxsYpzWscy5m2JtQi1y1KD0JZ9-Q6CrGTW34HXOskkOEd9KZ_FlRS2YRI7HzqMmY7fncOcAhml-ZVA3wpgKw3KM6RWR4QDa2P3lPAmfq_LYJy00gUdUovOxpJaYQ4Ka1y0MPzLKA_Bwyn2agSP6TP3y_fAR_pJlMIoEk2AwYSNYgiDHr8OIXuAc98CSWxyELscgXrwLbfBloD__tESp0wfaR4hmAGJQU7gWXlLS6u2iDWAiVj6gvskAGcNwnGEH0KZfDPpNYyyV44A4gHR1ar2A

### Create an order
POST http://localhost:8000/api/v1/orders/create
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjE0MTczNTUsImV4cCI6MTY2NDAwOTM1NSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckB1c2VyLmNvbSJ9.i90aHhuI1QdLH82kU05ehmGwkv0WtMcnQhdJ2Qp2RbdjkxvEtYIYbmwbsJ-ACMBxnkyRAFjA4H86Lh8wo_pgGWYu5qEhdSewty6d4A7ZOt5ZkiwiWL5aQwB12MRQP4nHhOdNSWG-PQwEYk5CAG9RrQZEJFggodK7vUjAUJfZAkQ-fLr0zSD0NBts068siVJmLBSx3NiJC7TCERDRooNHcONmpryCg7rzJpJ6lCNU7O-l_weqzQ9sYqTnKHEQl_v3k-0dANJVlTSNd9mSFEgvXrOtJ2v_n9hERHZY7Xamc_jfzu0P85nCzZnH23rJsFvJ4ZMehZSMR2ft2ZYnjrVuKA

{
"price": "13.90",
"depot": 41,
"orderProducts": [
    {
    "quantity": "1.000",
    "id": 121
    },
    {
    "quantity": "1.000",
    "id": 122
    }
],
"cartOrders": [
    {
    "quantity": 1,
    "id": 17
    },
    {
    "quantity": 1,
    "id": 18
    }
]
}