### Categories list
GET http://localhost:8000/api/v1/categories

### Category Products (fruits)
##
## http://localhost:8000/api/v1/categories/{slug}/products
GET http://localhost:8000/api/v1/categories/fruits/products

### Category Products (legumes)
GET http://localhost:8000/api/v1/categories/legumes/products

### Category Products (produits-transformes)
GET http://localhost:8000/api/v1/categories/produits-transformes/products

### Products list
GET http://localhost:8000/api/v1/products

### One product (poivron)
##
## http://localhost:8000/api/v1/products/{slug}
GET http://localhost:8000/api/v1/products/poivron

### Depots list
GET http://localhost:8000/api/v1/depots

### One depot (jordane-flatley)
##
## http://localhost:8000/api/v1/depots/{slug}
GET http://localhost:8000/api/v1/depots/jordane-flatley

### All carts
GET http://localhost:8000/api/v1/carts

### little cart
GET http://localhost:8000/api/v1/carts/small

### big cart
GET http://localhost:8000/api/v1/carts/big

### Create an order
POST http://localhost:8000/api/v1/orders/create
content-type: application/json

{
    "user": {
        "token": "user"
    },
    "depot": {
        "id": "1" 
    },
    "price": 0,
    "payment_status": "no",
    "cart": {
        "type_cart": "small",
        "quantity": 0
    },
    "product": {
        "id": "1",
        "quantity": 0
    }
}